In [2]:
import numpy as np

In [3]:
data=np.load("part1b.npz")

In [4]:
data.files

['N', 'Lc', 'Ic_0', 'gamma', 'L_validation', 'L_test', 'betas_validation']

In [5]:
data["N"]

array(50000.)

In [81]:
data['Lc'].shape

(4,)

In [7]:
data['Ic_0']

array([[47, 90, 51, 65],
       [82, 31, 64, 86],
       [30, 66, 39, 47],
       [59, 26, 77, 38],
       [20, 63, 70, 15],
       [35, 31, 78, 11],
       [50, 55, 93, 26],
       [17, 89, 65, 25],
       [70, 27, 66, 97],
       [20, 18, 32, 31],
       [76, 13, 61, 15],
       [86, 48, 36, 89],
       [96, 15, 44, 71],
       [81, 53, 19, 36],
       [29, 44, 99, 36],
       [25, 34, 16, 28],
       [23, 84, 71, 31],
       [91, 70, 90, 90],
       [32, 11, 68, 81],
       [34, 37, 48, 41]], dtype=int64)

In [8]:
data["L_validation"]

array([[  151.15723798,   157.09236032,   166.0663423 ,   175.26894184,
          187.12271809,   200.29536627,   207.19011153,   220.23944915,
          235.52590645,   247.09469931,   263.51055631,   281.18896107,
          304.53407513,   316.7776232 ,   337.4146583 ,   359.08603642,
          376.95873111,   410.63777058,   432.23666001,   466.32640805],
       [  168.20103748,   175.31698233,   184.41546073,   191.23318015,
          200.38958258,   212.84378649,   222.09570163,   237.44506788,
          251.13497681,   263.20329764,   281.12505942,   299.02683147,
          312.07088043,   336.08191882,   353.17466265,   372.3214408 ,
          404.21116271,   424.09816716,   450.52039605,   482.72819186],
       [  108.25555772,   116.61301613,   122.162737  ,   128.61290071,
          136.27974903,   143.16249542,   153.75545994,   158.05373752,
          171.84080869,   178.44468654,   190.6241656 ,   202.74814433,
          214.01601724,   233.09216822,   246.84519371,   265.

In [21]:
Lc.shape

(4,)

In [102]:
leaf_nodes=(np.array([[.5,.3,.1,.1],[.4,.3,.2,.1],[.3,.3,.2,.2],[.1,.2,.3,.4]])*data["N"])
lf=leaf_nodes.reshape(-1,1)
L_val=data["L_validation"]
Lc=data['Lc']
Lc1=Lc.reshape(-1,1)
betas_v=data["betas_validation"]
Ic_0=data['Ic_0'].reshape(-1,1)
#Ic=Ic_0.flatten()
t=np.linspace(0,20,21).reshape(-1,1)
I=np.sum(Ic_0)
Gamma=data["gamma"]
initial_v=np.concatenate([leaf_nodes.flatten(),Ic_0.flatten(),Lc1.flatten()])
print(initial_v[:16].reshape(-1,4))
print(initial_v[16:96].reshape(20,4))
print(initial_v[96:100].reshape(1,4))

[[25000. 15000.  5000.  5000.]
 [20000. 15000. 10000.  5000.]
 [15000. 15000. 10000. 10000.]
 [ 5000. 10000. 15000. 20000.]]
[[47. 90. 51. 65.]
 [82. 31. 64. 86.]
 [30. 66. 39. 47.]
 [59. 26. 77. 38.]
 [20. 63. 70. 15.]
 [35. 31. 78. 11.]
 [50. 55. 93. 26.]
 [17. 89. 65. 25.]
 [70. 27. 66. 97.]
 [20. 18. 32. 31.]
 [76. 13. 61. 15.]
 [86. 48. 36. 89.]
 [96. 15. 44. 71.]
 [81. 53. 19. 36.]
 [29. 44. 99. 36.]
 [25. 34. 16. 28.]
 [23. 84. 71. 31.]
 [91. 70. 90. 90.]
 [32. 11. 68. 81.]
 [34. 37. 48. 41.]]
[[0.3 0.4 0.7 1. ]]


In [109]:
def SIR(t,y,betas,gammas):
    S_vec=y[:16].reshape(-1,4)
    I_vec=y[16:96].reshape(-1,4)
    L_vec=y[96:100].reshape(-1,4)
    N=50000 ##population size 
    L=0
    
    
    dsvc_dt=-(betas*S_vec*sum(I_vec)/N)
    dic_dt=-(np.sum(dsvc_dt,axis=0))-(gammas*I_vec)
    dr_dt=gammas*sum(I_vec)
    L=I_vec*L_vec
    vectors=np.concatenate([L.flatten()])
    return vectors.reshape(-1,1)

In [117]:
from sklearn.metrics import mean_squared_error
from scipy.integrate import solve_ivp
beta_grid=np.linspace(0.001,1,16).reshape(-1,4)

bb=beta_grid

mmse=np.inf
beta_mmse=np.nan

print(initial_v.shape)
for b in beta_grid:

    def SIR(t,y,betas,gammas):
        S_vec=y[:16].reshape(-1,4)
        I_vec=y[16:96].reshape(-1,4)
        L_vec=y[96:100].reshape(-1,4)
        N=50000 ##population size 
        L=0
    
    
        dsvc_dt=-(betas*S_vec*sum(I_vec)/N)
        dic_dt=-(np.sum(dsvc_dt,axis=0))-(gammas*I_vec)
        dr_dt=gammas*sum(I_vec)
        L=I_vec*L_vec
        vectors=np.concatenate([L.flatten()])
        return vectors.reshape(-1,1)
    
    
    solution=solve_ivp(SIR,(t[0],t[-1]),initial_v,args=(bb,Gamma),dense_output=True)
    solutions = soln_obj.sol(t)
    local_mmse=np.inf


(100,)


ValueError: operands could not be broadcast together with shapes (4,4) (400,4) 